Spanish translation
semaphore-protocol/website pull request #59
Opened 2023-01-13 05:46 UTC by 0xyNaMu

## Description
As discussed, I have changed and added the main technical terms back in English and provided only the Spanish translation  in the first instance.

This has been applied across al pages. I cancelled the previous pull request so that this review supersedes the previous one! (which hopefully works haha) 

## Related Issue

## Other information

2023-01-13 20:09 UTC, aguzmant103 commented on i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.md
> +Para utilizar y verificar su identidad, la persona dueña de la identidad (usuario) debe conocer los valores trapdoor y nullifier.
trapdoor y nullifier podrian estar en comillas "" similar a la linea 34 para cambiar el formato y dar visibilidad de las palabras clave. es una sugerencia nada mas (que no la tiene en ingles)

2023-01-13 20:13 UTC, aguzmant103 commented on i18n/es/docusaurus-plugin-content-docs/version-V3/quick-setup.md
> +El CLI [`semaphore`](https://github.com/semaphore-protocol/semaphore/tree/main/packages/cli) también se puede utilizar para obtener información agregada de una red compatible (por ejemplo: `semaphore
sera mejor "informacion de un grupo"?

2023-01-13 20:17 UTC, aguzmant103 commented on i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/contracts.md
> +así como [**Semaphore.sol**](/docs/technical-reference/contracts#semaphoresol), el principal contrato desplegado en las redes que dan soporte para Semaphore.
"en las redes soportadas por Semaphore" ?

2023-01-13 20:19 UTC, aguzmant103 requested changes
Añadi unas pequeñas sugerencias, pero de aparte de eso esta genial!

2023-01-17 02:06 UTC, 0xyNaMu commented on i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.md
> +Para utilizar y verificar su identidad, la persona dueña de la identidad (usuario) debe conocer los valores trapdoor y nullifier.
Entiendo que aquí no llevan otro formato ya que se está hablando del valor mismo (es decir el número mismo, 1, 2, 3, etc) y no confundirlo con  una variable. 

Pero, sugiero que lo pongamos en italicas qye también se utiliza para denotar otros puntos relevantes como identity secret después y identity commitment que también son términos clave. :) 
¿Qué opinas @aguzmant103?

2023-01-17 02:40 UTC, aguzmant103 approved these changes

2023-01-17 02:41 UTC, aguzmant103 commented on i18n/es/docusaurus-plugin-content-docs/version-V3/guides/identities.md
> +Para utilizar y verificar su identidad, la persona dueña de la identidad (usuario) debe conocer los valores trapdoor y nullifier.
Creo que me retracto del feedback entonces :) @0xyNaMu como lo tenias originalmente esta super!

2023-01-17 04:30 UTC, vplasencia approved these changes

2023-01-17 04:30 UTC, vplasencia commented on i18n/es/docusaurus-plugin-content-docs/version-V3/technical-reference/contracts.md
> +En un futuro se inclurán más extensiones.
```suggestion
En un futuro se incluirán más extensiones. 
```

2023-01-17 04:30 UTC, vplasencia commented on i18n/es/docusaurus-plugin-content-docs/version-V3/what-is-semaphore.md
> +Semaphore utiliza contratos internos a la cadena en Solidity y librerias de JavaScript externas a la cadena que funcionan de forma conjunta.
```suggestion
Semaphore utiliza contratos internos a la cadena en Solidity y librerías de JavaScript externas a la cadena que funcionan de forma conjunta.
```

2023-01-17 04:30 UTC, vplasencia commented on i18n/es/docusaurus-plugin-content-docs/version-V3/what-is-semaphore.md
> +Semaphore está diseñado para ser un _componente de privacidad_ simple y genérico para aplicaciones decentralizadas (dApps) en Ethereum. Promueve el diseño modular de las aplicaciones, lo que permite
```suggestion
Semaphore está diseñado para ser un _componente de privacidad_ simple y genérico para aplicaciones descentralizadas (dApps) en Ethereum. Promueve el diseño modular de las aplicaciones, lo que permite que los desarrolladores de las dApps escojan y personalicen los componentes que necesitan externos e internos a la cadena.
```

2023-01-17 04:30 UTC, vplasencia commented on i18n/es/docusaurus-plugin-content-docs/version-V3/what-is-semaphore.md
> +-   Externos a la cadena (off-chain), se pueden utilizar librerias de Javascript para crear identidades, organizar grupos y generar pruebas.
```suggestion
-   Externos a la cadena (off-chain), se pueden utilizar librerías de Javascript para crear identidades, organizar grupos y generar pruebas.
```

2023-01-20 11:11 UTC, merged